### ISSUE TITLE
styled-components 사용법

### ISSUE THREAD

**Issue by kangsinbeom** [helloworld442/react-pagingnation#1]
민승님
styled component를 쓴거 보면서 궁금한건데...
common파일에 빼놓은 두개 jsx는 라우팅하면서 styled을 다시 쓴게 맞나요?
그리고 이거 어디에서 component 선언?? 그거 한건가요 못찾겠네요~

완성품 보려고 옆에 링크 들어갔는데 이상하게 나와서 나중에 시간나면 링크도 고쳐주세요~

자주 들르겠슴둥 오늘 바빠보여서 이슈로 궁금한거 남김다
나중에 굳이 오셔서 안말해주셔도 이슈로 적어주시면 제가 확인하겠슴다

화이팅~

**Comment by helloworld442** [comment]
common 폴더는 Box,Button 등 굉장히 많이 쓰이는 component들을 모아둔 폴더입니다. 이들을 왜 묶어냐면 바로 재 사용성 때문에 그렇습니다. 즉 나중에는 Button , Box 등은 나중에도 정말 많이 사용되기 때문에 common폴더에 넣은 것입니다 ㅎㅎ
